// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKX2gzPN9W-4QECILLahsoAXSnl6ZCts4',
    appId: '1:1059225375649:web:def40335504285239cf1e0',
    messagingSenderId: '1059225375649',
    projectId: 'courier-delivery-app-93ad0',
    authDomain: 'courier-delivery-app-93ad0.firebaseapp.com',
    storageBucket: 'courier-delivery-app-93ad0.firebasestorage.app',
    measurementId: 'G-T3CNBCCGZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTNxw4qTIgwjrvnYbSUsVvwZzeHOO2lT4',
    appId: '1:1059225375649:android:1841c90fe80ad3149cf1e0',
    messagingSenderId: '1059225375649',
    projectId: 'courier-delivery-app-93ad0',
    storageBucket: 'courier-delivery-app-93ad0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkNK9WlkDEyExqRpZQixo0DQnMUSmGeo4',
    appId: '1:1059225375649:ios:70145c81435175699cf1e0',
    messagingSenderId: '1059225375649',
    projectId: 'courier-delivery-app-93ad0',
    storageBucket: 'courier-delivery-app-93ad0.firebasestorage.app',
    iosBundleId: 'com.example.courierDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkNK9WlkDEyExqRpZQixo0DQnMUSmGeo4',
    appId: '1:1059225375649:ios:70145c81435175699cf1e0',
    messagingSenderId: '1059225375649',
    projectId: 'courier-delivery-app-93ad0',
    storageBucket: 'courier-delivery-app-93ad0.firebasestorage.app',
    iosBundleId: 'com.example.courierDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKX2gzPN9W-4QECILLahsoAXSnl6ZCts4',
    appId: '1:1059225375649:web:6814fd0618f2643b9cf1e0',
    messagingSenderId: '1059225375649',
    projectId: 'courier-delivery-app-93ad0',
    authDomain: 'courier-delivery-app-93ad0.firebaseapp.com',
    storageBucket: 'courier-delivery-app-93ad0.firebasestorage.app',
    measurementId: 'G-ET48EZXS4N',
  );
}
